window.onload = function () {
    list = ["Teresita Sanchez",
    "Ivy Patdu",
    "Nadine  Abela",
    "Julio  Andres III",
    "Joanne Denise Asuque - Quevedo",
    "Dyan Marie Austral",
    "Aimee Flor Barrion",
    "Nina Bella",
    "Joy  Bellen ",
    "Serafin V Bernardo",
    "Valerie Anne Blas",
    "Penafrancia  Cano",
    "Ana Maria Consuelo ",
    "Dennis David ",
    "Richard Escolar ",
    "Melissa Editha  De Leon ",
    "Chlenice Dela Cruz",
    "Allan Garcia",
    "Joseph Joven  Gammad",
    "Alexander Gui",
    "Therese Hautea",
    "Michael John Hilario",
    "Marinelle Layo-Laguna",
    "Alice Madayag",
    "Katheleen Maturan",
    "Frank Nacario",
    "Joniday  Nieva",
    "Maria Teresa   Paelmo",
    "Fidel Payawal",
    "Mary Ellen  Perez",
    "Erlita Querubin",
    "Ma. Asuncion Reyes",
    "Maria Dolma  Santos",
    "Edgard Simon",
    "Don Benjamin Serrano",
    "Luretta Tayao",
    "Cristina Tiongson",
    "Maila Tiolengco-Badillo",
    "Benjamin Daniel Valera",
    "Maria Sonia Yee-Festin",
    "Johanna Patricia Canal",
    "Michael Martin Malabanan",
    "Michael Benedict Mejia",
    "Enrico Tangco",
    "Jean Arevalo",
    "Bernadette Cecille Borromeo",
    "Rafael Felix Borromeo",
    "Geraldine  Campos",
    "Myra Joyce Cenido",
    "Liza Divierte",
    " Mercedes Glendora De Villa",
    "Jose  Francisco",
    "Mariejecelle Lim",
    "Emma Natividad",
    "Pamela Sue Natividad-Mendoza",
    "Patricia Natividad-Sumagpao",
    "Ma. Victoria Novenario",
    "Michael Andrew Magtoto",
    "Maria Janet  Pandan",
    "Peter Pandan",
    "Joaquin Edward Rosero",
    "Leandro Rosero",
    "Daniel  Samaniego",
    "Luis Gerardo  Sunico",
    "Hazel Marie  Tala",
    "Maria Xenia Velmonte",
    "Hermogenes  Villareal",
    "Maria Shervy Monica Villareal",
    "Sherwin Villareal",
    "Maria Sheryl  Villareal-Borja",
    "Vivian  Virata",
    "Aissa Celeste Aguilar - Almeda",
    "Bernadette  Arcilla",
    "Maria Rosario Leonor Arceo",
    "Mary Jane Arzadon",
    "Maria Olga  Bernardo - Del Moral",
    "Ma. Angela  Cumagun",
    "Janet  De Grano",
    "Jose Giovanni  Dimayuga",
    "Virgie Ritz Dy",
    "Katty  Estrada",
    "Ma. Teresita  Gabriel",
    "Anne Marie Gamboa",
    "Anna Gracia Garcia",
    "Ethel  Garcia",
    "Arsenia  Guiang",
    "Pamela Guiang",
    "Noemi  Guloy",
    "Contessa Louise Hamada-Ostrea",
    "Evangeline  Handog",
    "Leilani  Hinlo",
    "Mariliza Javalera-Echivarre",
    "Maria Beatriz  Lagos",
    "Johanna Pauline  Lazo-Dizon",
    "Carmela Ana  Lim",
    "Elize Maria Therese Lim",
    "Jacqueline Madulid-Luna",
    "Wilhelmina  Maniquis",
    "Francis Michael Marcelino",
    "Clarisse Mendoza",
    "Filomena  Montinola",
    "Ma. Estela  Montano",
    "Marie Eleanore  Nicolas",
    "Beverly Ong- Amoranto",
    "Maria Natalia Orig-Palma",
    "Ma. Melissa Pasion - Dabao",
    "Charina Ann Pelayo",
    "Jeni Pua",
    "Claire Marie Reyes- Habito",
    "Cristina Regina Reyes",
    "Leilani   Senador",
    "Loverna  Suratos",
    "Cristina Tan",
    "Aivee Teo",
    "Ma. Socorro Toledo",
    "Edna May  Tranquilino",
    "Ma. Elena  Villacorta",
    "Irene Gaile  Robredo-Vitas",
    "Kristina Ann Abenes",
    "Esteban Almeda",
    "Mary Frances Bernardo",
    "Venus Calingasan",
    "Ma. Christina Cedilla",
    "Mark Lester Coronel",
    "Maria Janelle Custodio",
    "Mark Benedict Ebreo",
    "Amado Flores III",
    "Carlos Vicente Gabriel",
    "Ma. Jennifer Gacad",
    "Manolito Jose  Gacad",
    "Grace Hernandez",
    "Paolo Roman Hernandez",
    "Fleurdeliz  Kallos- Guinto ",
    "Eden Lasala",
    "Mary Grace Lim",
    "Martin Eugene Anthony Luna",
    "Eligio Santiago Maghirang",
    "Nannede  Mercado",
    "Ma. Avo Elise Ortega",
    "Paolo Edgardo Palad Jr.",
    "Marc Lamberto Reyes",
    "Richard Albert San Luis",
    "Edgar Jolly Santos",
    "Abegail Teodorica Sumang",
    "Maria Lourdes Suntay",
    "Cesar Neil Syquia",
    "Vergel  Tatco",
    "Rhoderick Tiongson",
    "Patricia Tiotuico",
    "Vilmor Tusing",
    "Gracita Ybiernas",
    "Conrado Yutuc",
    "Gerardo Briones",
    "Aaron Mark Hernandez",
    "Joanne Robles",
    "Jovillia Abong",
    "Manuel  Canlas",
    "Cesar Joseph  Gloria",
    "Cherie Ocampo-Cervantes",
    "Nelson  Abelardo",
    "Maria Teresa Abola",
    "Ferdinand Alzate",
    "John  Anonuevo",
    "Jeremias Jr. Balgua ",
    "Ma. Cecilia Bondoc",
    "Amelita  Brillantes",
    "Arcalucy Cabalu",
    "Esperanza  Cabral",
    "Emiliano Jr. Canonigo",
    "Patrick  Carpo",
    "Robert Leomark  Castro",
    "Ernesto  Chua",
    "Sotero, Jr. Crisostomo",
    "Joel Dela Rosa",
    "Wilfred  Dee",
    "Christopher Delos Reyes",
    "Lourdes  Diaz",
    "Jude James Espejo",
    "Gilbert Florentino",
    "Juan Dionisio Marcelino Foronda",
    "Giselle Gervacio-Domingo",
    "Daisy Jarcia",
    "Saturnino  Javier",
    "Joaquin Emilio Fausto Jison",
    "Anthony  King",
    "Noel Lapus",
    "Amor  Lauro",
    "Eleanor  Lopez",
    "Gary  Lopez",
    "Felipe III Lorenzo",
    "Wilmer Vicente Lotilla",
    "Benjamin Jr. Luna",
    "Alan Regin Malvar",
    "Apollo Mondelo",
    "Ruben Ortega",
    "Fabio Enrique  Posas",
    "Alejandro Prieto",
    "Paul Quetua",
    "Dolores Quianzon",
    "Maritoni Rapadas- Ilao",
    "Michael Joseph Reyes",
    "Simon Sawit",
    "David Raymund Salvador",
    "Oliver Sansano",
    "Luigi Pierre Segundo",
    "Maita Senadrin ",
    "Ma. Rosario  Sevilla",
    "Maria Carmelita Somera",
    "Maria Helga Sta. Maria",
    "Joel Tanedo",
    "Richard Henry II Tiongco",
    "Francisco  Tranquilino",
    "Laurencia  Trinchera",
    "Gracita  Topacio",
    "Ofelia  Valencia",
    "Gerald  Vilela",
    "Earl Fidel Villareal",
    "Jay Michael Yason",
    "Leanne Therese Zuniega",
    "Laura Rosario  Acampado",
    "Marie Yvette Maura Amante",
    "Monica Therese Cabral",
    "Kristine Denise Corvera",
    "Maria Arlene Crisaldo",
    "Thelma  Crisostomo",
    "Rowena De Jesus",
    "Joy Arabelle  Fontanilla",
    "Margarita Victoria Galicia",
    "Ma. Cecilia Gonzales",
    "Franceslina Ang",
    "Augusto  Litonjua",
    "Cynthia Rosanna Manabat",
    "Lynn Wagan - Bilar",
    "Gia  Wassmer",
    "Angelica Joy Alonte",
    "Sol  Alvarez",
    "Marceliano Jr. Aquino",
    "Wilfrida Aguirre - Jison",
    "Patricia Anne Cabral - Prodigalidad",
    "Rommel Calinisan",
    "Jane Campos",
    "Agustin Ceniza",
    "Antonio  Comia",
    "Frederick Dy",
    "Alvin  Jimenez",
    "Madalinee Eternity  Labio",
    "Rona Marie Lawenko",
    "Marie Antoinette Lontok ",
    "Marc  Lustre",
    "Ruter Maralit",
    "Ma. Isidra Apolonia Masa",
    "Gerardo Mendoza",
    "Eulenia  Nolasco",
    "Jose Celso  Novenario",
    "Alvin Quino",
    "Ronald Romero",
    "Maria Nelia Runes",
    "Jose Jr. Sollano",
    "Karla Maria Suzara",
    "Hildegarde  Vistal",
    "Anna May Agdamag",
    "Francisco Vicente  Lopez",
    "Pia Angela Receno",
    "Jesus   Relos",
    "Salvador  Abad Santos",
    "Joseph Adrian Buensalido",
    "Mari Rose  Delos Reyes",
    "Edwin  Dimatatac",
    "Jemelyn Garcia",
    "Marion Priscilla Kwek",
    "Jodor  Lim",
    "Thelma Tupasi",
    "Angelita  Aguirre",
    "Orlina Alcantara",
    "Arby  Baybay",
    "Jerry  Castro",
    "Maria Regina  Chuatico",
    "Buenaventura Eric Desquitado",
    "Leonila Eseque",
    "Robert Michael Gan",
    "Genato Gene Gomez",
    "Peter  Kaliski",
    "Ma.Susan Lim",
    "Joanna Malana-Mackay",
    "Dean Manuel",
    "Roberto  Salvino",
    "Wilfredo Saulog",
    "Marian   Suarez",
    "Enrico  Tolentino",
    "Mark Untalan Jr.",
    "Delia  Bayog",
    "Margrette Ruth Bernardo",
    "Brian Michael Cabral",
    "Silvino Martin Jr. Corpuz",
    "Tyrone Francis Coseip",
    "Gladys Maribal Diaz",
    "Maria Isabel Duavit",
    "Maria Ailsa Escobin",
    "Pelagio, Jr. Esmaquel",
    "Vincent Paul Filio",
    "Lynn  Gomez",
    "Regina  Liboro-Tan",
    "Arlene Marcelo",
    "Melvin  Marcial",
    "Roderic Ng",
    "Dinah Luisa  Paralisan",
    "Claver  Ramos",
    "Josierina Sarmiento",
    "Joanne Marie Balbuena - Arcillas",
    "Gerardo Tomas  Cornelio",
    "Eunice Theres Cutillar",
    "Conrado Gabriel, III Lorenzo",
    "Mary Ondinee Manalo-Igot",
    "Cherry Marquez",
    "Corazon Ngelangel ",
    "Josephine Tolentino",
    "Maria Karen Luisa Villanueva-Timbol",
    "Ma. Pamela Patdu",
    "Ethel  Anonuevo",
    "Ma. Rowena Balcita",
    "Veyda Christine Bringas",
    "Earl Richardson Chua",
    "Noel  Fabian",
    "Lenora  Fernandez",
    "Andrew Gonzales",
    "Eduardo  Jamora",
    "Manuel Antonio Ko",
    "Nazario Jr. Macalintal",
    "Ronald Antonio Reodica",
    "Shelley Romero",
    "Mary Jane Sandagon",
    "Maria Isabel Samaniego",
    "Joven Jeremius  Tanchuco",
    "Michelle Angela Tan-Reyes",
    "Clemente  Amante",
    "Eric Jason Amante",
    "Hannah Rowena Espiritu",
    "Jose Paulo  Lorenzo",
    "Evelyn  Salido",
    "Rosario Marie  Sarmiento",
    "Michael   Tee",
    "Frederick  Acampado",
    "Ma. Socorro  Alejandrino",
    "Regina  Canlas",
    "Alvin Rae Cenina",
    "Ma. Cecilia  De Guzman",
    "Cid Czarina Diesta",
    "Josephine  Gutierrez",
    "Ana Marie  Javelosa",
    "Henry  Lu",
    "Angel Luna",
    "Corina Maria Socorro  Macalintal",
    "Vincent Macalintal",
    "Arman Oronce",
    "Ma. Celeste Pena",
    "Anthony  Piano",
    "Jesus Alberto  Poblete",
    "Cymbeline  Perez-Santiago",
    "Aubrey  Punzalan",
    "Josephine  Tuason",
    "Joel Gabriel Colasito",
    "Eusebio  Debuque",
    "Adonis Bernabe  Gascon",
    "Vladimir Hufana",
    "Almario Jabson",
    "Gerardo Legaspi",
    "Jean Quint Oropilla",
    "Michael Sabalza",
    "Carlos Francis Santiago",
    "Kenny Seng",
    "Roy Allan Dominique Torcuator",
    "Jay Villavicencio",
    "Rene Angodung",
    "Ramon  Basa",
    "Maria Serena Bawalan",
    "Maria Regina Blas - Quismorio",
    "Rumalie Corvera",
    "Roy Cuison",
    "Lemuel Del Rosario",
    "Mylene Escritor",
    "Noeline Russel Esguerra-Cutchon",
    "Eliza Mei Belen Francisco",
    "Dennis James Gabriel",
    "Marissa Antonette Garcia",
    "Carla Frances Lazaro-Feraer",
    "Rommel Lerpido",
    "Maricel Mangrobang",
    "Jerttie Rhea Mendoza",
    "Marie Evangeline  Mendoza",
    "Paul Nierva",
    "Arabelle Coleen Ofina",
    "Elena Ramirez",
    "Regina Rugayan ",
    "Stephanie Caroline Sabularse",
    "Kelly Salvador",
    "Aries Silva",
    "Angeli Venus",
    "Marikka Thaenia Solana",
    "Maria Antonia Yamamoto",
    "Hellene Claire Abastillas",
    "Maria Fatima Acojido",
    "Maria Imelda Antonia Almeda-Fernando",
    "Lynn Amurao",
    "Anne Mahalia Angeles",
    "Leon Aquino",
    "Martha  Aquino",
    "Ma. Charina Rose Arrienda-Romano",
    "Rosemin Balbido",
    "Mario Benito Bautista",
    "Bernardita  Brion",
    "Andrew Rouldan Buizon",
    "Maria Angela Rodriguez - Bandola",
    "Glenn Gaspar Raymund Benitez",
    "Ana Marie  Burgos",
    "Anna Maria Bella  Cagayan",
    "Arminda  Calayan",
    "Teresita Cantos - David",
    "Emma Caringal",
    "Leonila Casanova",
    "Maria Del Carmen Castillo",
    "Paciencia  Cauilan",
    "Violeta  Celis",
    "Geanie  Cerna - Lopez",
    "Maria Rosario Cheng",
    "Lily Rose Co",
    "Elisa Patricia May  Cornelio",
    "Lyvia  Corpuz",
    "Mary Judith Clemente",
    "Ma. Cristina Pelaez - Crisologo",
    "Conrado Crisostomo",
    "Aldabelle Cruel",
    "Josefa  Cruel",
    "Jerusha Cruz",
    "Amelia  Dacanay",
    "Godofreda  Dalmacion",
    "Lena  Danao",
    "Elsie Dancel",
    "Heidi  Dauigoy",
    "Moonyeen De Asis - Noble ",
    "Mailanie Grace De Cadiz",
    "Erwin De Mesa",
    "Marie Aleli De Castro",
    "Blanca  De Guia",
    "Ma. Corazon  De Jesus",
    "Gemmari  Dela Merced",
    "Sonia  Desquitado",
    "Edwin Agustin  Dimayuga",
    "Efren Domingo",
    "Ma. Elena  Domingo",
    "Madeline  Florendo",
    "Maria Nerizza Flores",
    "Lany  Gabilo",
    "Judith Galang-Perez",
    "Esther Rhadamanthine Jr. Ganzon",
    "Maria Lalaine Garcia",
    "Myrna  Garrido",
    "Lilibeth Genuino",
    "Anafe Gloria",
    "Maria Elena Gomez",
    "Anabelle  Guilot",
    "Valerie  Guinto",
    "Shiela Marie Hernandez",
    "Ellen Joy Ignacio",
    "Ina Irabon",
    "Elizabeth  Jacinto",
    "Stella Marie  Jose",
    "Mariet  Labanen",
    "Enrique  Labios",
    "Susana Lao",
    "Nanette  Laurente",
    "Ma. Aurora Lazarte",
    "Leonor Leonardo",
    "Ma. Socorro  Lim",
    "Ma. Katherine Lipana",
    "Cecilia  Llave",
    "Maria Theresa  Lopez",
    "Alberto  Madrilejo",
    "Rena Cristina  Malaya",
    "Medina  Malit",
    "Manuel  Manabat",
    "Maria Regina  Manahan",
    "Maria Asuncion Manalastas ",
    "Eileen  Manalo",
    "Joan Manaloto- Mangubat",
    "Ma. Luisa  Mangubat",
    "Catherine Irene  Medina",
    "Cleofe Medina",
    "Mary Evangeline Mercado",
    "Laureen Honor Mondragon",
    "Cecil  Monteblanco",
    "Ernesto, Jr. Naval",
    "Mariel Nevado- Gammad",
    "Ann Kathryn Nunez-Roces",
    "Maria Angelina O' Santos",
    "Enrico Gil Oblepias",
    "Maria Victoria Olivares",
    "Annette Cecille  Olondriz",
    "Zeanath  Palala",
    "Cecilia  Pavilion",
    "Carmen Adela  Perez",
    "Satrina Rica Perez-Castillo",
    "Loida  Ponio",
    "Lisa Teresa Prodigalidad-Jabson",
    "Ma. Linda  Quevedo",
    "Belen  Rajagukguk",
    "Julie Resurreccion",
    "Marie Catherine Grace Remollino",
    "Cynthia  Reyes",
    "Ma. Cecilia  Reyes",
    "Maria Niza  Reyes",
    "Ramon Emilio Daniel Roces",
    "Aina  Sales Diaz",
    "Michael Angelo  Sales Diaz",
    "Marietta Samoy",
    "Filomena San Juan",
    "Aurora  Sandoval",
    "Evangeline Santos",
    "Sheryl Santos-Tan",
    "Diana  Sarmiento",
    "Kristine Sese",
    "Elsa  Singh",
    "Rebecca  Singson",
    "Sherri Ann Suplido",
    "Gladys  Tanangonan",
    "Maria Lora  Tansengco",
    "Christine Vivienne Succor Tantoco",
    "Ma.Gloriphine II Torres ",
    "Milagros  Torres",
    "Arlene  Tuazon",
    "Cesar  Ubaldo",
    "Virginia Valenzuela",
    "Rita Linda Velez",
    "Fe  Vergara",
    "Guadalupe  Villanueva",
    "Salvador Luis Villanueva",
    "Maria Regina Villar - Rivera",
    "Mae Villareal",
    "Paulita  Villegas",
    "Phyllis Carl Ybera",
    "John David  Zamora",
    "Leah Anne  Zamora",
    "Jessica Marie  Abano",
    "Benjamin Jr. Abela",
    "Ma. Rowena Asuncion  Adiviso",
    "Joshua Aguilar",
    "Simeon Emmanuel II  Aquino",
    "Alan Gerard Austriaco",
    "Juanchito Jr.  Bernardo",
    "Angelica Cabero - Santos",
    "Noel  Carino",
    "Joselito  Casimiro",
    "George Emmanuel Comia",
    "Danilo II Constantino",
    "Jose Luis  De Grano",
    "Maria Hannah Pia De Guzman",
    "Fabian Arnel De Jesus",
    "Gilbert  Dela Cruz",
    "Jimmy Walter, Jr. Dinglasan",
    "Grace Dizon - Grozman",
    "Edgardo Ulysses  Dorotheo",
    "Irene Marie Enriquez",
    "Marie Antonette Eltanal - Pascual",
    "Roderick  Feliciano",
    "Fernandino Jose Fontanilla",
    "Lionel Raymond Francisco",
    "Clarissa Gonzales",
    "Maria Gracia  Gutay",
    "Gabriel Juan Heredia",
    "Mark Anthony Imperial",
    "Karlo Jacob",
    "Juan Antonio Javellana",
    "Irene Jocson",
    "Renato Jose",
    "Roumel Litao",
    "Maria Christina  Manas",
    "Peggy Ann Manese",
    "Leonardo  Mangubat",
    "Tricia Andrea Madrid",
    "Jesus  Marin",
    "Jose Maria Martinez",
    "Daniel Jacinto  Mijares",
    "Jamie Lynne Narciso",
    "Roel Nunez",
    "Vicente Victor Jr. Ocampo",
    "Suzanne Katrina Palafox",
    "Erwin Palisoc",
    "Cesar, Jr. Perez",
    "Maria Angelina Punzalan-Tirol",
    "Salvador Quianzon",
    "Raquel Quino",
    "Gertrude Gwendale Reinoso",
    "Catherine Dianne Reyes- Delfino",
    "Rigo Daniel Victor Emmanuel Reyes",
    "Ma. Ysabel Reyes-Catindig",
    "Maria Joanna  Rodriguez-Chan",
    "Barbara Roque",
    "Manolette  Roque",
    "Beverly Rosas",
    "Dino Ruiz",
    "Edmin Michael Santos",
    "Rodrigo  Senador",
    "Roseny Mae  Singson",
    "Antonio Elmer  Tan",
    "John Baldwin Tan",
    "Mary Rose  Teodoro",
    "Bernard Gil Tinio ",
    "Edward Uy",
    "Ramon Valenzuela",
    "Kent Wee",
    "Fernando Acance",
    "Larry Acuna",
    "Ruben  Arafiles",
    "Frederick  Aujero",
    "Gregorio Marcelo Azores",
    "Carlo Angelo Borbon",
    "Mark Gabriel Barreiro",
    "Carlo Angelo Belen",
    "Marcelino Cadag",
    "Antonio  Calanoc",
    "Marc Anthony Castro",
    "Adrian  Catbagan",
    "Dave Anthony Dizon",
    "Albert Cesar, Jr. Faller",
    "Jose Alfonso Gonzales",
    "Angel  Gozum",
    "Jerome Joseph Grageda",
    "Samuel Arsenio Grozman",
    "Ilustre Jr. Guloy",
    "Ramon Gustilo",
    "Jose Anthony Jocson",
    "Terence Leveriza",
    "Mark Allen Lopez",
    "Roberto Gabriel Lopez",
    "Jose Miguel Lumawig",
    "Michael  Marfori",
    "Edwin  Mercado",
    "Eric John  Morales",
    "Michael  Munoz",
    "Frederick Patrick  Nicomedez",
    "Rolando Angelo  Ochoa",
    "Orson  Odulio",
    "Nathaniel Orillaza",
    "Jose Martin  Paiso",
    "Juan Carlos Paredes",
    "Ellewellyn  Pasion",
    "Enrique Leonardo Pasion",
    "Manuel III Pecson ",
    "Godofredo, Jr. Pineda",
    "Antonio  Puti",
    "John Hubert Pua",
    "Rolando Puno",
    "Alan Leonardo  Raymundo",
    "Antonio  Rivera",
    "Jonathan Ronquillo",
    "Francis Joseph Reyes",
    "Edward  Sarrosa",
    "Edwin Jerd  Siatan",
    "Ana Rosario Merceditas Sta. Ana",
    "Irewin Tabu",
    "Ambrosio Emilio III Valdez",
    "Miguel Enrique  Valencia",
    "Edward Wang",
    "Fitzderick Zarate",
    "Generoso  Abes",
    "Franco Louie Abes",
    "Keith Romeo Aguilera",
    "Eduard Alfanta",
    "Tomas Ang",
    "Kathrina Aquino-Diaz",
    "Jaime Anthony Arzadon",
    "Arsenio Claro Cabungcal",
    "Christopher Malorre Calaquian",
    "Julie Cebrian",
    "Reyvic Cerilles",
    "Ansberto  Co",
    "Teresa Luisa  Cruz",
    "Abegayle Machelle  Chua",
    "Anthony Charles Dalmacio",
    "Elpidio Jesus Dominguez",
    "Cecile Trisha Duran",
    "Ma. Lourdes Enecilla",
    "Mary Apple Pie Garcia",
    "Efren Jr. Gutierrez",
    "Ma. Fita  Guzman",
    "Josefino  Hernandez",
    "Melfred  Hernandez",
    "Emmanuel  Ibay",
    "Anne Elizabeth Sanz",
    "Raymond Vincent  Jurilla",
    "Ramon Antonio  Lopa",
    "Geraldine  Luna",
    "Ernest Roberto Manas",
    "Norman  Mendoza",
    "Felix  Nolasco",
    "Roberto  Pangan",
    "Patrick Joseph Pardo",
    "Renato Jr. Pascual",
    "Maria Rosario Pillas",
    "John Michael Porquez",
    "Agnes  Remulla",
    "Edgardo Jr. Rodriguez",
    "Juan  Rosas",
    "Alvin  Tapia",
    "Raynald Edlin Torres",
    "Manuel Jr. Villegas",
    "Nathaniel  Yang",
    "Robie  Zantua",
    "Agustina Abelardo",
    "Jose Maria Avila",
    "Maria Teresa  Castillo",
    "Arvin Faundo",
    "Imelda Marie Fremielle Flores - Palacol",
    "Nelson Geraldino",
    "Paulo Giovanni  Mendoza",
    "Edwin Munoz",
    "Maria Ana  Abe",
    "Ma. Mercedita Alcala",
    "Geraldine  Alcantara",
    "Ruth Margaret  Alejandro",
    "Edna Anyayahan-Saguros",
    "Jocelyn  Aromin",
    "Rubi Diana Avisado",
    "Maria Micaela Marciana Baduria",
    "Dory Buena",
    "Miraflor  Bunye",
    "Miguel  Celdran",
    "Catherine  Cinco",
    "Pamela  Caedo",
    "Rosalinda  Crespo",
    "Virginia  Crisostomo",
    "Josephine  Cruz",
    "Jonathan Cu",
    "Edward Vincent Dauigoy",
    "Ma. Julita  Debuque",
    "Carmela De Lara",
    "Barbara Ann Ejercito-Manio",
    "Marie Arlene  Estevez- Genio",
    "Elvira  Estorninos",
    "Amelia Fernandez",
    "Evelyn Sheila  Galedo",
    "Macario, Jr. Galvez",
    "Maria Agatha Garcia",
    "Janice Stephanie Gimenez-Mendoza",
    "Elynn Go ",
    "Angela Gomez",
    "Genaro Jesse Gonzales",
    "Gwendolyn  Gonzales",
    "Jea Halum",
    "Socorro Hao",
    "Phyllis Bernadette Kapuno",
    "Sandra Litao",
    "Trinidad Marie  Lombos",
    "Wilhelmina Lopez",
    "Ruth Lorico",
    "Maria Margarita Lota",
    "Mercedes Victoria  Lotilla",
    "Mercedita  Macalintal",
    "Gemma  Maggay",
    "Ma. Cristina Ana Magno - Rivera",
    "Ma. Arlene Mary - Balasbas",
    "Marevelyn Matic",
    "Job  Mingoa",
    "Victor Gerardo  Morada",
    "Elizabeth Ann  Morales",
    "Arnel  Nuguid",
    "Romeo  Nuguid",
    "Aimee Marie Nunez-Regala",
    "Shirley Josefina  Ong",
    "Anne  Orendain",
    "Maria Victoria Paiso",
    "Crispulo Ulysses III Patdu",
    "Maria Concepcion  Paulino",
    "Larcie Principe",
    "Josephine  Quintos-Apostol",
    "Florence Rivera",
    "Teresa Maria Ribano",
    "Ma. Sherlita Rosario",
    "Benjamin Jr. Sablan",
    "Jeanette Samson",
    "Sherry Vi Sarra",
    "Vienne de Lou  Saulog",
    "Paulene Ver Serna-Zarate",
    "Marilou  Songco",
    "Abigail Pia Suntay",
    "Michelle Syquia",
    "Josephine Policar",
    "Mylene Teves",
    "Florentina Ty",
    "Harriet Valencia",
    "Erickson Viola",
    "Normelita  Zalamea",
    "Evangeline Zozobrado",
    "Ma. Emma  Llanto",
    "Maria Cristina Caguioa",
    "Joel  Lazaro",
    "Ma. Anna Lourdes Moral",
    "Lucia Liz Aliwalas",
    "Marian  Colasito",
    "Rita Josephine Dolendo",
    "Christopher Grageda",
    "Janelle Margaux Logronio",
    "Jacinto Blas Mantaring III",
    "Socorro Mendoza",
    "Ma. Eleanor  Sia",
    "Caroline Gloria",
    "Marysia Stella Recto",
    "Maria Patricia Santos-Abes",
    "Fatima Johanna  Santos-Ocampo",
    "Juliet Balderas",
    "Jose Jonas  Del Rosario",
    "Maria Concepcion Sison",
    "Kim Martin Tolentino",
    "Jade Marie Torralba-Visaya",
    "Jean Antonio Villareal",
    "Alvin  Florentino",
    "Dan  Malate",
    "Hannah Vera Villamor",
    "Michael  Wassmer",
    "Sylvia  Estrada",
    "Portia Monreal",
    "Maria Imelda Belen Vitug - Sales",
    "Maria Melanie Liberty Alcausin",
    "Cynthia Rosario  Castro",
    "Michelle Rodriguez",
    "Allan Robert Racho",
    "Ma. Rosario  Capeding",
    "Benjamin Co",
    "Salvacion Gatchalian",
    "Ma. Lourdes  Gozali",
    "Josephine Anne Ng",
    "Ma. Carmen  Nievera",
    "Maria Tricia Subido",
    "Charissa Fay Corazon Tabora",
    "Beatrice  Canonigo",
    "Czarina  Canosa",
    "Rita  Mendoza",
    "Ma. Karen Quin",
    "Joseph Zoilo Zablan",
    "Carolyn Butler",
    "Kristine Latorre - Mendoza",
    "Madeleine Grace Sosa",
    "Bernadette Terencio",
    "Maria Corazon Avancena",
    "Ma. Victoria  Cabahug",
    "Devino  Garcia",
    "Shiela Monzon",
    "Luis  Rivera",
    "Luis Roberto Jr. Rivera",
    "Fanny Gae Sermise-Gadian",
    "Arneil  Suratos",
    "Joselito  Teves",
    "Rozaida Villon",
    "Christine Bernal",
    "Carmina Bernardo",
    "Melanie Anne Cardenas",
    "Jon Edward  Jurilla",
    "Elaine Angela Leynes",
    "Maria Madeline Mallillin",
    "Jesus Alberto  Poblete",
    "Marie Kristine Roldan",
    "Eleonor Sanchez-Antonio",
    "Salvador Benjamin Vista",
    "Maria Corazon Cabuquit",
    "Marta Socorro Cruz",
    "Jerico Dela Cruz",
    "Franklin Domingo",
    "Rosita Estabillo",
    "Teresita Joy Evangelista",
    "Melissa  Gozum",
    "Ma. Arlene Ledesma",
    "Joseph Gerard Lipana",
    "Geraldine Montes ",
    "Victoria Fresita Morales",
    "Michael Francis Obispo",
    "Helen Grace Pesigan",
    "Peter Henry Adapon",
    "Yvette Eve Bernabe Datu-Ramos",
    "Abigail Borja",
    "Alfredo, Jr. Calendacion",
    "Ruthanne Capito",
    "Ronald Cervantes",
    "Emelyn De Jesus ",
    "Catherine  De Larrazabal",
    "Imarzen Elepano",
    "Catherine  Garcia",
    "Cicero Matthew Habito",
    "Harlee Ilao",
    "Primo, Jr. Laforteza",
    "Noree Jane Lastrilla",
    "Eddie Lim ",
    "Abigayl Lopez",
    "Lord Euclid Anthony Loreto",
    "Alfredo Madamba",
    "Manuel Madayag",
    "Manuel Jr. Mejia",
    "Abigail Milo",
    "Jasmin Narvaez",
    "Antonio Marlo Nievera",
    "Ma. Fahrdilen Puray -Guanzon",
    "Frederick Benjamin Quing",
    "Vicente, Jr. Romano",
    "Vicente, Jr. Ruben",
    "Belinda San Juan",
    "Ramon Augusto Hilarion Santos-Ocampo",
    "Maria Theresa Tabu",
    "Robert Tan-Gatue",
    "Joan Uy-Valdez",
    "Leizl Valerio",
    "Tirso Jr. Velasco",
    "Karlos Noel Aleta",
    "Samuel Andin",
    "Avenilo, Jr. Aventura",
    "Joseph  Barril",
    "Ronnie Cacas",
    "Gisel Catalan",
    "Calixto, Jr Chan",
    "Mariam Grace Delima",
    "Adrian Peter Desquitado",
    "Dennis de Asis",
    "Ramon Jr.  Diaz",
    "Peter Figueroa",
    "Robin Augustine Flores",
    "Jorge  Garcia",
    "Roberto Gerardo Ignacio",
    "Emmanuel, Jr. Jarcia",
    "Roger Michael Lim",
    "Karyn Luna",
    "Anthony Manlulu",
    "Gerardo Manzo",
    "Richard Nicolas",
    "Francisco Peralta Jr.",
    "Pio Purino, Jr.",
    "Racel Ireneo Luis Querol",
    "Merceditas Althea Quinon",
    "Karl Michael Reyes",
    "Ramon Ribu",
    "Aquileo Rico",
    "Edgar Tuazon",
    "Junico Visaya",
    "Sherwin  Alamo",
    "Romarico Rommel, Jr. Azores",
    "Carlos  Magsanoc",
    "Ramon Francisco Estrada",
    "Marc Paul Lopez",
    "Omar Ocampo",
    "Manuel Francisco  Roxas",
    "Gaudencio Abratique",
    "Alberto Jose Albano",
    "Teodorico Arambulo",
    "Mariano Jr. Atacador",
    "Rouel Mateo  Azores",
    "Aldine Astrid Basa",
    "Apolinario Ericson  Berberabe",
    "Xavier Bituin",
    "Alfred Allen Buenafe",
    "Melanie Cruz",
    "Carlo Canosa",
    "Arlyn Canones ",
    "Angel  de Larrazabal",
    "Emmanuel Diaz",
    "Eduardo  Eseque",
    "Jose Macario Faylona",
    "Tito  Garrido",
    "Malen Gellido",
    "Francis  Gundran",
    "Gavino Gino Roberto Herman",
    "Herbert Lansangan",
    "Juan, Jr. Lim",
    "Antonio  Macapagal",
    "Honorato Jr. Mackay",
    "Norman Manlapaz",
    "Beverlee Verona Mante",
    "Marwin Emerson Matic",
    "Karl Morales ",
    "Gabriel Natividad",
    "Karen Nielsen",
    "Joseph Thomas Noriega",
    "Alfonso III Nunez",
    "John Francois Ojeda",
    "Felicidad Claudia Ordonez",
    "Roel Pena",
    "Leo  Principe",
    "Rannie Rabe",
    "Raymundo Resurreccion",
    "Constancio Reyes",
    "Rolando  Reyes",
    "Filadelfo Juan Alberto III Rojas ",
    "Warren Roraldo",
    "Laren Saguros",
    "Roehl Salvador",
    "Ignacio  San Gabriel",
    "Allen Anthony Sese",
    "Alejandro Jose Singson",
    "Charlton Sibal",
    "Ferdinand  Syfu",
    "Vitus Talla",
    "Rhodel Torrijos",
    "Vittoria Vanessa Velasquez",
    "Pio Renato Villacorta",
    "Jaime Jr. Villamin",
    "Anthony Yap",
    "Shirard Leonardo  Adiviso",
    "Crisostomo Jr. Arcilla",
    "Ralph Allan Bicol",
    "Elmer Bondoc",
    "Marcus Jose  Brillantes",
    "Arvin Briones",
    "Peter Noel Calub",
    "Janeth Carreon ",
    "Roland Cinco",
    "Arnel  Diaz",
    "Orlando  Diomampo",
    "Ricardo Dizon, Jr.",
    "Manuel Gerardo, Jr. Dulay",
    "Carlos, Jr. Ejercito",
    "Rico Estrella",
    "Marlow Esguerra",
    "Miguel Gary Galvez",
    "Michael  Lawenko",
    "Nathaniel Labio",
    "Anthony Lim",
    "Ronaldo Gerardo Lopez",
    "Joaquin  Manalastas",
    "Edgar  Mendiola",
    "Rolando  Mendiola",
    "Miguel  Mendoza",
    "Roderick Mujer",
    "Karen Nielsen",
    "Raymund Andrew Ong ",
    "Mervyn Anthony Orocio",
    "Ernest Jerome  Pagdanganan",
    "Anthony  Perez",
    "John Paul Allen Regala",
    "Rafael Alexis Resurreccion",
    "Jose Antonio  Salud",
    "Ray  Sarmiento",
    "Eva Lourdes Sta.Clara",
    "Ivor  Tantuco",
    "Romeo  Uyloan",
    "Bernard Victorio",
    "Russel Alegarbes",
    "Josefina Almonte",
    "Wilma  Baltazar",
    "Antonio Catangui",
    "Anderson Lim ",
    "Marcus Lester Suntay",
    "Rodolfo Jr. Tuazon",
    "Ma. Celine Isobel Villegas",
    "Jorge  Concepcion",
    "Teodoro  Herbosa",
    "Maria Concepcion  Ortillo - General",
    "Marcelo Pacheco",
    "Raymundo Resurreccion",
    "Ernesto III Arada",
    "Bernardo Cabatingan",
    "Constantino, III Castillo",
    "Emilio III Cano",
    "Arturo, Jr. Castro",
    "Jose Dante  Dator",
    "Aldrin Joseph Gamboa",
    "Michael John Francis Gaston",
    "Ernesto Gerial Jr.",
    "Francis Raymund Gonzales",
    "Demetrio Hadap",
    "Jonathan Gil Lao",
    "Emmanuel  Lenon",
    "Reynaldo Madrinan",
    "Nikko Magsanoc",
    "Francis Silvestre  Perez",
    "Francis John Pile",
    "Abelardo  Prodigalidad",
    "Jose Vicente  Prodigalidad",
    "Benjamin Jr. Ramos",
    "Lou Chris  Allen Reyes",
    "Silverio  Salileng",
    "Rolando Guillermo Saulog",
    "Dennis  Serrano",
    "Jaime  Songco",
    "Carlos Ramon Jr. Torres",
    "Manuel Jr. Yuhico",
    "Hermenegildo Jose Zialcita",
    "Marco Jose Fulvio Abad",
    "Antonio Roberto Abaya",
    "Alejandro  Aquino",
    "Leo Carlo Baloloy",
    "Victor  Gisbert",
    "Esteban Jonathan III Lacson",
    "Paul Jesus Montemayor",
    "Enrique Ona",
    "Ricardo  Quintos",
    "Arwin Ronan Ronsayro",
    "Martin Anthony Villa",
    "Eric Perpetuo Arcilla",
    "Vicente  Castillo",
    "Tristan Albert Catindig",
    "Jose Joven  Cruz",
    "Glenn Angelo  Genuino",
    "Benjamin  Herbosa",
    "Florencio Lucero",
    "Francisco  Manalo",
    "Ponciano  Manalo",
    "Marlon Marquina",
    "Nicanor Cesar Bruno Montoya",
    "Nikki Eileen Salvano - Valencia",
    "Mark Cornelius Sison",
    "Bernard Tansipek",
    "Ma. Irene Tangco",
    ];
    var t = creatSlotMachine
        ($(".slotMachineContainer")[0], list);
    setTimeout(function () {
        putList(t.list, list)
    }, 50),
 $(".screen .confirm").on("click", function () {
     $(".prize").hide("nomal", function () {
         $(".screen").css("display", "none")
     })
 }), $(t.button).on("click", function () {
     animateButton($(t.button)), t.joysticks.addClass("joysticksAnimate"), setTimeout(function () {
         t.joysticks.removeClass("joysticksAnimate")
     }, 1850), drawARaffle(t, list)
 }).css("cursor", "pointer")
};