//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raffle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public System.Guid event_id { get; set; }
        public string event_name { get; set; }
        public System.DateTime event_date { get; set; }
        public string event_location { get; set; }
        public System.DateTime start_datetime { get; set; }
        public System.DateTime end_datetime { get; set; }
        public byte[] event_banner { get; set; }
        public Nullable<bool> delete_flag { get; set; }
        public Nullable<System.DateTime> deleted_datetime { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public int passcode { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public string email_address { get; set; }
        public Nullable<int> starttime_ref_id { get; set; }
        public Nullable<int> endtime_ref_id { get; set; }
        public Nullable<bool> onLive { get; set; }
        public Nullable<int> participant_count { get; set; }
        public Nullable<short> hasRaffle { get; set; }
        public Nullable<short> registration_req { get; set; }
        public Nullable<bool> closed_flag { get; set; }
        public Nullable<System.DateTime> closed_datetime { get; set; }
        public Nullable<bool> reopen_flag { get; set; }
        public Nullable<System.DateTime> reopen_datetime { get; set; }
    }
}
