//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raffle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public System.Guid event_id { get; set; }
        public string event_name { get; set; }
        public System.DateTime event_date { get; set; }
        public string event_location { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public byte[] event_banner { get; set; }
        public Nullable<bool> delete_flag { get; set; }
        public Nullable<System.DateTime> deleted_datetime { get; set; }
        public int passcode { get; set; }
    }
}
